### ISSUE TITLE
brink allure with opentherm

### ISSUE THREAD

**Issue by louisvangeldrop** [raf1000/brink_openhab#2]
I have a Brink Allure 25 with Opentherm support. Will the ventilator/fan tsp parameters also work for this heater?

**Comment by raf1000** [comment]
I am not  able to confirm, as my whole knowladge is based on the exisitng documentation of Brink Renovent HR and number of experiments. The first step is to  compare  the Brink Renovent HR`s parameters with Brink Alure function based on the documentation of these both appliances. If the meaning (ans also sequence?) of paramteres are  the same/smillar (ex U, I etc) one can assume that is shall be compatible.
