### ISSUE TITLE
Connection issues with Brink renovent sky 300

### ISSUE THREAD

**Issue by Cortog** [raf1000/brink_openhab#3]
Hello,

I have bought the same shield as you have to connect a Wemos d1 mini to my Brink renovent sky 300. However, I'm not able to get a connection with it. I plugged the shield onto the Wemos and made a cable to connect to the port normally used for the "Brink air control" ([pdf page 19, document 15](https://www.brinkclimatesystems.nl/documenten/renovent-sky-300-612378.pdf)). 
First I uploaded your Brink_HR.ino file. I checked to see if messages were appearing in the MQTT server, they were, but all the responses were "0". The green LED on the shield was flashing about once every second when the cable was plugged in. 
To debug I used [this](https://github.com/Sidiox/hrv-control/blob/master/scanner/scanner.ino) arduino sketch which sends a request to all ID's from 0 to 254. I saw that all the responses were "0", and the OpenThermResponseStatus was either INVALID or TIMEOUT. 

My question to you is: did you have to change anything about the Brink unit to communicate with it? Mine is one month old and has not been connected to a "Brink air control" or any other form of control unit.

**Comment by raf1000** [comment]
I haven`t good news for you :-(  After having a look at the Brink Air 300 manual you are referring to I have not found info about integration with Opentherm. Chapter 5.4.2 page 19 refers to eBUS connection. This is a different protocol and conector than opentherm. There are some ebus connectors avaiable  but mainly for heating((I am using one for Vaillant)). You need search further if there is any solution for ventilation/Brink as well...

**Comment by Cortog** [comment]
Thanks anyway. I guess I must have confused Opentherm and eBUS at some point during my search
