### ISSUE TITLE
Compilation Error OpenTherm.cpp

### ISSUE THREAD

**Issue by tijsverkoyen** [raf1000/brink_openhab#5]
When I try to compile the program I get:

```
~/Documents/Arduino/libraries/OpenTherm_Library/src/OpenTherm.cpp: In member function 'uint16_t OpenTherm::getBrink2TSP(BrinkTSPindex)':
~/Documents/Arduino/libraries/OpenTherm_Library/src/OpenTherm.cpp:448:25: error: 'response2' was not declared in this scope; did you mean 'response'?
  448 |  return isValidResponse(response2) ? getUInt(response |= response1 << 8) : 0;
      |                         ^~~~~~~~~
      |                         response
~/Documents/Arduino/libraries/OpenTherm_Library/src/OpenTherm.cpp: In member function 'bool OpenTherm::setBrink2TSP(BrinkTSPindex, uint16_t)':
~/Documents/Arduino/libraries/OpenTherm_Library/src/OpenTherm.cpp:478:1: error: control reaches end of non-void function [-Werror=return-type]
  478 | }
      | ^
cc1plus: some warnings being treated as errors
```

I replaced the files `OpenTherm.cpp` and `OpenTherm.h` in `~/Documents/Arduino/...` with the ones you have [provided](https://github.com/raf1000/brink_openhab/tree/main/Arduino).

I'm a novice when it comes to Arduino IDE, so probably I am doing something wrong. Any help would really be appreciated! Let me know if you need more info.

**Comment by raf1000** [comment]
Hello, 
There was an error in the code. I have corrected. Please try to compile again. If there are still problems I will have look at it next week/or I will load the whole sorce code again. Let me know.
